# Generated by Django 5.2.8 on 2026-08-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_code",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("machine_model", models.CharField(db_index=True, max_length=150)),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("purchase_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DEPLOYED", "Deployed"),
                            ("UNDER_SERVICE", "Under Service"),
                            ("INACTIVE", "Inactive"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MachineAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField()),
                ("returned_date", models.DateField(blank=True, null=True)),
                (
                    "assignment_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RETURNED", "Returned")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machine_assignments",
                        to="clients.client",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="machines.machine",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client", "assignment_status"],
                        name="machines_ma_client__7ecd04_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("assignment_status", "ACTIVE")),
                        fields=("machine",),
                        name="one_active_assignment_per_machine",
                    )
                ],
            },
        ),
    ]
