# Generated by Django 5.2.8 on 2026-08-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["inventory_item", "transaction_date"],
                name="inventory_i_invento_71614e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_quantity__gte", 0)),
                name="inventory_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_stock_level__gte", 0)),
                name="inventory_minimum_nonnegative",
            ),
        ),
    ]
