# Generated by Django 5.2.8 on 2026-08-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_inventorytransaction_inventory_i_invento_71614e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("BEVERAGE_INGREDIENT", "Beverage Ingredient"),
                    ("CONSUMABLE", "Consumable"),
                    ("MACHINE_SUPPLY", "Machine Supply"),
                    ("CLEANING_SUPPLY", "Cleaning Supply"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
