# Generated by Django 5.2.8 on 2026-08-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE_SERVICE", "Routine Service"),
                            ("CLEANING", "Cleaning"),
                            ("REPAIR", "Repair"),
                            ("INSPECTION", "Inspection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("technician_name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "previous_machine_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_records",
                        to="machines.machine",
                    ),
                ),
            ],
        ),
    ]
